### ISSUE TITLE
owlbot: owlbot is never run without manual label on java-bigtable-hbase

### ISSUE THREAD

**Issue by kolea2** [googleapis/repo-automation-bots#2705] opened 2021-10-12 14:19 UTC
Hi! The java-bigtable-hbase repo is never picked up by owlbot and we always need to add the owlbot:run tag in order for it to work. Here's a recent example: https://github.com/googleapis/java-bigtable-hbase/pull/3284. Are we missing any configs?

**Comment by SurferJeffAtGoogle** [comment] 2021-10-13 16:59
Doh.  Owl Bot ran for my pull request:
https://github.com/googleapis/java-bigtable-hbase/pull/3289

**Comment by SurferJeffAtGoogle** [comment] 2021-10-13 17:49
I'm closing this bug because I can't repeat it.  The next time you see it, please re-open this issue.  We'll have better information in the logs to debug what happened.

**Comment by kolea2** [comment] 2021-12-06 16:30
@SurferJeffAtGoogle I think I figured out what the issue is - it seems to not work on PRs from forks. Is this expected behavior?

**Comment by bcoe** [comment] 2021-12-20 19:52
@kolea2 it's expected behavior that it won't run against forks, the problem is that if a fork was made by an untrusted individual, they could point to a malicious docker container that runs code in cloud build -- similar to kokoro, we opted to make it necessary to add a `run` label, as a security measure.

**Comment by SurferJeffAtGoogle** [comment] 2022-01-04 23:34
I think Owl Bot is working as intended.  It won't run automatically on pull requests from untrusted people.  That's a security requirement.

**Closed by SurferJeffAtGoogle** 2022-01-04 23:34 UTC
Labels: type: bug, priority: p2
