### ISSUE TITLE
Release please not proposing a release PR for google-cloud-java monorepo 

### ISSUE THREAD

**Issue by ddixit14** [googleapis/repo-automation-bots#4157] opened 2022-08-17 00:51 UTC
Trying to implement release-please for [google-cloud-java ](https://github.com/googleapis/google-cloud-java) but release please is not proposing a PR after "releasable units" are committed to the default branch. CLI states "timeout".

**Comment by suztomo** [comment] 2022-08-17 01:59
@ddixit14 Add your observations. Screenshots and suspicious log messages.

**Comment by ddixit14** [comment] 2022-08-17 16:57
@chingor13 (Adding observations that might be of some use)

**Timeout Error logs:**
https://cloudlogging.app.goo.gl/c4XxyKBy6eSZQHpV9
https://cloudlogging.app.goo.gl/edLJ3F2pYArBUAW4A

**Logs for one invocation** - https://drive.google.com/file/d/1khFoyzzOOfwkDa3Yd7Oqkiy9cNAoLvBI/view?usp=sharing&resourcekey=0-VWI9rSoX2qXZXWGGmXDi8Q

After looking at the logs, only 83/126 [modules](https://github.com/googleapis/google-cloud-java/blob/monorepo_script_output/.release-please-manifest.json#L2-L83) are getting processed before the timeout (approx 9 minutes). Doing an approximation, if the timeout is increased to 15 mins, it should be able to process all the modules.

**Comment by tmatsuo** [comment] 2022-08-17 18:42
Here is an excerpt from the log:

> message: "Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F64D:8CDF:650E49:133FA82:62FC3CC6` when reporting this issue."}]}: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F64D:8CDF:650E49:133FA82:62FC3CC6` when reporting this issue."}]}"
name: "GitHubAPIError"
stack: "HttpError: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F64D:8CDF:650E49:133FA82:62FC3CC6` when reporting this issue."}]}
    at /workspace/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async /workspace/node_modules/release-please/build/src/github.js:68:38
    at async GitHub.graphqlRequest (/workspace/node_modules/release-please/build/src/github.js:1000:20)
    at async GitHub.pullRequestsGraphQL (/workspace/node_modules/release-please/build/src/github.js:655:26)
    at async GitHub.pullRequestIterator (/workspace/node_modules/release-please/build/src/github.js:626:30)
    at async Manifest.findSnoozedReleasePullRequests (/workspace/node_modules/release-please/build/src/manifest.js:463:26)
    at async Manifest.createPullRequests (/workspace/node_modules/release-please/build/src/manifest.js:424:37)
    at async Function.Runner.createPullRequests (/workspace/build/src/runner.js:23:5)
caused by: HttpError: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F64D:8CDF:650E49:133FA82:62FC3CC6` when reporting this issue."}]}
    at /workspace/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async /workspace/node_modules/release-please/build/src/github.js:68:38
    at async GitHub.graphqlRequest (/workspace/node_modules/release-please/build/src/github.js:1000:20)
    at async GitHub.pullRequestsGraphQL (/workspace/node_modules/release-please/build/src/github.js:655:26)
    at async GitHub.pullRequestIterator (/workspace/node_modules/release-please/build/src/github.js:626:30)
    at async Manifest.findSnoozedReleasePullRequests (/workspace/node_modules/release-please/build/src/manifest.js:463:26)
    at async Manifest.createPullRequests (/workspace/node_modules/release-please/build/src/manifest.js:424:37)
    at async Function.Runner.createPullRequests (/workspace/build/src/runner.js:23:5)"
status: 502
type: "GitHubAPIError"

**Comment by tmatsuo** [comment] 2022-08-17 18:48
Currently `release-please` cloud function is using the first generation runtime and has 540 second timeout.

**Comment by tmatsuo** [comment] 2022-08-17 19:04
The maximum timeout for Cloud Function first generation is 540 seconds, but it's 3600 seconds for the second generation.

Potentially we can use the second generaiton runtime (`--gen2` flag for gcloud) with a longer timeout, but I'm not sure how compatible the second generation runtime is and whether the bot will work fine, or not.

**Comment by tmatsuo** [comment] 2022-08-17 19:10
Another option for having a longer timeout is to use Cloud Run directly (Cloud Function gen2 is built on top of Cloud Run). Some bots are already using Cloud Run as the backend server, so it might be an easier option for us.

**Comment by chingor13** [comment] 2022-08-17 21:57
I will work on moving it to Cloud Run and other API call optimizations (it's running a pom.xml search like 60 times)

**Comment by chingor13** [comment] 2022-08-19 23:21
release-please is now failing on graphQL queries when trying to find snoozed PRs

**Comment by chingor13** [comment] 2022-08-24 17:18
Now failing with: https://github.com/googleapis/code-suggester/issues/397

The pull request commit is too large for the GitHub API -- we'll need to split into multiple commits

**Comment by suztomo** [comment] 2022-08-24 18:08
@chingor13 It's possible google-cloud-java repository regenerated the monorepo_script_output branch.

**Closed** 2022-08-26 18:55 UTC
Labels: type: bug, priority: p2
