### ISSUE TITLE
Build Cop: duplicate issues for same test failure?

### ISSUE THREAD

**Issue by shollyman** [googleapis/repo-automation-bots#283] opened 2020-02-14 17:39 UTC
Unclear why we're getting multiple bugs for the same test:

https://github.com/GoogleCloudPlatform/python-docs-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+test_ncaa_tutorial

Currently yields 4 issues for the same test:
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2892
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2891
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2849
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2800

**Comment by tbpg** [comment] 2020-02-14 18:02
My first thought was that this was a race condition when parallel runs finish at the same time. But, it looks like some of those issues were filed days apart.

https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2892 and https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2891 look like a race condition.

I'm not sure why the other issues aren't being found (or, only found sometimes).

**Comment by tbpg** [comment] 2020-02-16 15:00
The problem is pagination. There are > 32 Build Cop issues in python-docs-samples: https://github.com/GoogleCloudPlatform/python-docs-samples/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22buildcop%3Aissue%22

But, we currently only get the first 32 issues. So, it's just luck with whether or not the already-existing issue is returned/found.

https://github.com/googleapis/repo-automation-bots/blob/4dd6255014d43296f0393fd84d807747525f2d74/packages/buildcop/src/buildcop.ts#L115-L123

Pagination docs are here: https://octokit.github.io/rest.js/#pagination

I'll send a PR.

**Comment by tbpg** [comment] 2020-02-16 15:00
Part of the fix needs to include closing duplicate issues, maybe preferring to keep an issue someone other than the bot has commented on.

**Comment by tbpg** [comment] 2020-02-18 17:43
For some reason, we're getting many, many _duplicate_ comments on issues (sorry!)

Example: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2849

Looking.

**Comment by tbpg** [comment] 2020-02-18 19:04
All of the duplicate comments are because there are many, many sponge_log.xml files that get sent to the bot.

The bot then has a different instance for each one of the logs. They are all running at the same time,  they all try to close the duplicate issues, then they all comment at the same time.

I can't think of a way to prevent this race condition within the bot itself. So, one idea is to add some sort of external locking mechanism.

We could limit concurrency, but the same Cloud Function is used for every repo, so that would just slow things down.

**Closed** 2020-02-19 18:09 UTC
Labels: priority: p2, type: bug
