### ISSUE TITLE
infra: bot template/config for running on Cloud Run

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1817] opened 2021-05-20 16:02 UTC
In the future, we will want extra dependencies available to our bot. We should still be able to run our probot-based bots easily with our credentials and tasks shims in `gcf-utils` within a Docker container on Cloud Run.

- [x] Figure out how to run in Cloud Build
- [x] Configure canary-bot to run on Cloud Build
- [x] Configure scheduler-proxy to target a Cloud Build service
- [x] Configure gcf-utils to queue tasks to target the Cloud Build service
- [x] Configure generate-bot to templatize deployment for a new bot

**Comment by codedfiles** [comment] 2021-07-07 07:39
Duplicate of #

**Comment by codedfiles** [comment] 2021-07-07 07:50
> In the future, we will want extra dependencies available to our bot. We should still be able to run our probot-based bots easily with our credentials and tasks shims in `gcf-utils` within a Docker container on Cloud Run.
> 
> * [x]  Figure out how to run in Cloud Build
> * [x]  Configure canary-bot to run on Cloud Build
> * [ ]  Configure scheduler-proxy to target a Cloud Build service
> * [x]  Configure gcf-utils to queue tasks to target the Cloud Build service
> * [ ]  Configure generate-bot to templatize deployment for a new bot

**Closed** 2022-06-01 22:47 UTC
Labels: type: process
