### ISSUE TITLE
bug(owlbot): `owlbot:run` label does not trigger owlbot

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2437] opened 2021-09-02 21:26 UTC
In https://github.com/googleapis/python-datastream/pull/26, I've added the `owlbut:run` label but it is not triggering owlbot to run.

Some background: 
I'm testing a solution for https://github.com/googleapis/repo-automation-bots/issues/1790. In https://github.com/googleapis/python-datastream/pull/26,  I've updated the post processor image in `.OwlBot.lock.yaml` and `OwlBot.yaml` from `gcr.io/repo-automation-bots/owlbot-python:latest` to `gcr.io/cloud-devrel-public-resources/owlbot-python:latest` . I managed to get owlbot to run on the PR but, for some reason , I can't get owlbot to run again.

**Comment by bcoe** [comment] 2021-09-02 21:31
This is a duplicate of https://github.com/googleapis/repo-automation-bots/issues/2339

**Closed by bcoe** 2021-09-02 21:31 UTC
Labels: type: bug, bot: owl-bot
