### ISSUE TITLE
owlbot-maybe-create-pull-request-for-lock-update aren't running

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#2171] opened 2021-06-24 16:52 UTC
We should see a batch of these fire off every time there's an update to googleapis/synthtool.

The most recent run of owlbot-maybe-create-pull-request-for-lock-update was on 06/21/21. 

![image](https://user-images.githubusercontent.com/11778530/123302508-9ea81100-d4d1-11eb-9abe-844e4b281022.png)

However, there have been 5 commits to synthtool since 06/21/21:

![image](https://user-images.githubusercontent.com/11778530/123302703-d44cfa00-d4d1-11eb-9b46-e66b14971fc5.png)

**Comment by bcoe** [comment] 2021-06-24 19:58
The root cause of this issue seems to be that HTTP POST payloads that come in from pubsub are not passing signature validation, see:

https://github.com/googleapis/repo-automation-bots/pull/2172

There were two problems I noticed:

1. The signature validation doesn't actually return a `400` error, it returns a `200` which happens to have `statusCode` `400` in the payload; this made it hard to notice the underlying issue initially.
2. We need to figure out why our signature on the payload is wrong, my hunch is spacing in JSON?

**Comment by bcoe** [comment] 2021-06-25 16:18
this is now fixed on main, with @tmatsuo working on better fix.

**Closed by bcoe** 2021-06-25 16:18 UTC
Labels: bot: owl-bot, priority: p1, type: bug
