### ISSUE TITLE
OwlBot checks should be made to be required checks

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1714] opened 2021-05-03 18:55 UTC
I think the problem is that we're not calling the github API to announce that the check was kicked off.  We only call the github API when the check has completed.  There's a window of time when the user isn't aware that the Owl Bot check is running, and may merge.

For example, this PR was merged before Owl Bot post processor completed.
https://github.com/googleapis/python-security-private-ca/pull/35

CC @parthea

**Comment by bcoe** [comment] 2021-05-04 00:49
@SurferJeffAtGoogle the issue is that OwlBot would need to be declared to be a required check:

https://github.com/googleapis/repo-automation-bots/blob/master/packages/sync-repo-settings/src/required-checks.json

Only these types of checks block pull requests from being merged.

It's up to repository owners to decide what checks are required to have passed before a merge can take place ... the reason it's difficult to make OwlBot a required check right now, is that we're only partially migrated over.

**Comment by SurferJeffAtGoogle** [comment] 2021-05-11 20:21
Saw this again: https://github.com/googleapis/nodejs-binary-authorization/pull/47

**Comment by tmatsuo** [comment] 2021-05-20 01:22
Note:

If we use the owlbot checks in branch protection rules, then obviously owlbot needs to always create that check regardless of the result.

**Comment by SurferJeffAtGoogle** [comment] 2021-06-14 20:22
Another PR where I find no evidence of owl bot running: https://github.com/googleapis/java-aiplatform/pull/406

**Comment by parthea** [comment] 2021-06-14 20:53
@SurferJeffAtGoogle  I also have [this PR](https://github.com/googleapis/python-aiplatform/pull/475) currently in the failed state where owl bot is not running, even with the `owlbot:run` label.

**Comment by parthea** [comment] 2021-06-14 21:00
Update:  I had to remove and re-add the `owlbot:run` label to kick start owl bot.

**Comment by SurferJeffAtGoogle** [comment] 2021-06-16 22:43
@Neenu1995 saw another instance of Owl Bot post processor not running automatically: https://github.com/googleapis/java-analytics-data/pull/223

**Comment by bcoe** [comment] 2021-06-18 19:43
With regards to https://github.com/googleapis/java-aiplatform/pull/406, OwlBot was not running for PRs created from a fork, this has been fixed by #2106.

A potential cause of @Neenu1995's failing to run, is that a week ago we were seeing significant backlogs in our Cloud Build queue, I've increased our queue to 30 from 10 jobs, which will hopefully help with this category of bug.

On a case by case basis I'd like to ask that, if we observe OwlBot failing to run, we bring it up in the GitHub Automation chat as close to the time of the event as possible. There may be multiple things happening, and I'd like to catch them in the act:

* a WebHook failing to deliver.
* a backlog of jobs.
* an undiagnosed bug.

----

Now, coming back to the action item described in this issue....

To protect against landing bad code to a branch, I suggest enabling OwlBot as a required check, this has been done for Node.js ([here's how it's done](https://github.com/googleapis/repo-automation-bots/pull/2110)).

<img width="984" alt="Screen Shot 2021-06-18 at 12 32 12 PM" src="https://user-images.githubusercontent.com/194609/122608536-3d93bf80-d031-11eb-902e-a1f1c902a608.png">

If for whatever reason OwlBot fails to run, I then suggest (along with reporting the issue to us as close to the time of the event as possible) that you add the `owlbot:run` label to kick off the runner.

I'm closing this PR in favor of #2112 and #2113.

**Closed by bcoe** 2021-06-18 19:43 UTC
Labels: :rotating_light:, bot: owl-bot, priority: p1, type: bug
