### ISSUE TITLE
OwlBot: PRs are made to ReadOnly sub-repos for PHP

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#3531] opened 2022-04-28 20:46 UTC
When OwlBot generates a PR to the [main PHP Cloud repo](https://github.com/googleapis/google-cloud-php), it generates a corresponding PR to the sub-repos. For example:

 - https://github.com/googleapis/google-cloud-php-spanner/pull/6
 - https://github.com/googleapis/google-cloud-php-spanner/pull/7

These PRs will always be closed, because these repos are mirrored from the main PHP Cloud repo, and even if they were merged, they would be overwritten by the next release.

We only need to ever submit PRs to the main PHP Cloud repo. These additional PRs create extra noise, so it would be great to have them turned off.

**Comment by bshaffer** [comment] 2022-06-16 21:55
@SurferJeffAtGoogle This is still happening as of 22 hours ago: https://github.com/googleapis/google-cloud-php-dataplex/pull/5

**Comment by SurferJeffAtGoogle** [comment] 2022-06-21 23:32
The specific dataplex issue is due to unfortunate timing.  The fix landed a day later:
https://github.com/googleapis/repo-automation-bots/pull/3946

I confirmed it won't happen again because I see this line in scan config's logs:
`2022-06-21 05:07:51.286 PDT
Ignoring googleapis/google-cloud-php-dataplex and removing its configs from the database.`

**Closed by SurferJeffAtGoogle** 2022-06-21 23:32 UTC
Labels: type: bug, priority: p2, bot: owl-bot
