### ISSUE TITLE
[Owlbot] Owlbot is not following conventional commit

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#3302] opened 2022-03-17 19:19 UTC
In this pull request https://github.com/googleapis/java-pubsub/pull/993, Owlbot didn't follow conventional commit.

<img width="953" alt="Screen Shot 2022-03-17 at 3 15 22 PM" src="https://user-images.githubusercontent.com/28604/158879066-9631e382-e1aa-462b-938b-1033b5b27423.png">

Not critical. I can manually update the title by looking at corresponding CL.

**Comment by SurferJeffAtGoogle** [comment] 2022-03-18 16:27
I restored the PR title for that https://github.com/googleapis/java-pubsub/pull/993, and I'm investigating why it happened.

**Comment by suztomo** [comment] 2022-03-18 16:36
To supply more info, that pull request has weird (larger than usual?) changes https://github.com/googleapis/java-pubsub/pull/993#issuecomment-1071315600, not just the title.

CC: @anguillanneuf

**Comment by SurferJeffAtGoogle** [comment] 2022-03-18 17:05
This issue is a duplicate of https://github.com/googleapis/repo-automation-bots/issues/3216.  This incident occurred before the bug was fixed.

**Closed by SurferJeffAtGoogle** 2022-03-18 17:05 UTC
Labels: type: bug, priority: p2

**Comment by suztomo** [comment] 2022-03-18 17:46
@SurferJeffAtGoogle Thank you for investigation!
