### ISSUE TITLE
Owl Bot post processor running multiple times

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#3303] opened 2022-03-18 16:23 UTC
Is there already a bug open for this?  I couldn't find it.

Latest example:
https://github.com/googleapis/java-dialogflow/pull/861/commits

![image](https://user-images.githubusercontent.com/11778530/159042508-5644d953-b05f-4a47-bb42-bd49212fd53f.png)

**Comment by bcoe** [comment] 2022-03-19 15:47
@SurferJeffAtGoogle I believe the cause of this problem is containers that take longer than 540 seconds to execute, leading to a timeout in the cloud function. This in turn leds to a second run of the post-processing container.

A possible solution is switching to Cloud Run rather than Cloud Functions, which has a 1 hour timeout.

**Comment by tmatsuo** [comment] 2022-03-23 22:56
Moving to cloud run doesn't solve fundamental issue. If the post processor takes more than 1 hour, we will have the same problem.

Can we record the Cloud Build build and then resume if there's an existing build for that commit sha?

**Comment by bcoe** [comment] 2022-03-24 18:45
@tmatsuo in practice, I don't believe our longest builds are taking ~10 minutes (perhaps 15). So, I think extending the timeout could be a low cost way to prevent this category of bug without any engineering.

**Comment by bcoe** [comment] 2022-04-22 17:47
I think this will be fixed as soon as duration of tasks is increased, which I have work in progress to do.

**Comment by bcoe** [comment] 2022-04-27 22:07
The two most recent post-processor jobs that took longer than 10 minutes did not result in a double push to the PR:

See: https://github.com/googleapis/python-compute/pull/275

**Closed by bcoe** 2022-04-27 22:07 UTC
Labels: type: bug, priority: p2, bot: owl-bot
