### ISSUE TITLE
serverless-scheduler-proxy repeatedly exceeds container memory limit and spams our error logs

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1687] opened 2021-04-26 23:18 UTC
https://console.cloud.google.com/errors?time=PT6H&order=COUNT_DESC&resolution=OPEN&resolution=ACKNOWLEDGED&project=repo-automation-bots

The fact that it crashes isn't a big deal, because it restarts and gets back to work.  However, it makes it harder for us to identify real issues because it spams our error logs.

**Comment by SurferJeffAtGoogle** [comment] 2021-04-26 23:19
![image](https://user-images.githubusercontent.com/11778530/116162686-2b3d7b00-a6ab-11eb-8e3c-410ee1b1b3af.png)

**Comment by bcoe** [comment] 2021-05-04 00:56
We've been living with this for months, so I think we're okay to downgrade to `p2` to prevent it from impacting our SLOs for Node.js client libraries.

**Comment by tbpg** [comment] 2021-05-04 14:06
I added `pprof` to the proxy, ran it locally, deployed a Cloud Function, and sent traffic to the proxy using `curl`.

The cause of the leak is creating a new `secretmanager.Client` on every request and never closing them:
https://github.com/googleapis/repo-automation-bots/blob/bb95b740f56d4a0dd792a140b82396ff99340877/serverless-scheduler-proxy/main.go#L191-L194

The fix is adding `defer client.Close()` or sharing the `Client` between requests. I'll send a PR with the one-line `Close` call.

More detail follows below.

-----------------

Here is the Go code change to add `pprof` endpoints to the server:
```go
	mux.HandleFunc("/debug/pprof/", pprof.Index)
```

How I built and ran the proxy:
```
$ go build
$ PROJECT_ID=my-project PORT=8080 ./serverless-scheduler-proxy
```

The `curl` command I used:
```
for i in {1..500}; do
curl --header "Content-Type: application/json" --request POST --data '{"name": "HelloHTTP", "type": "testing", "location": "us-central1"}' localhost:8080/v0/cron
echo " -- $i"
done
```

Here is the `pprof` output when I had just started the server and had a few requests:
```
$ go tool pprof heap.0.pprof
File: serverless-scheduler-proxy
Type: inuse_space
Time: May 4, 2021 at 9:33am (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 2129.67kB, 100% of 2129.67kB total
Showing top 10 nodes out of 30
      flat  flat%   sum%        cum   cum%
 1089.33kB 51.15% 51.15%  1089.33kB 51.15%  google.golang.org/grpc/internal/transport.newBufWriter (inline)
  528.17kB 24.80% 75.95%   528.17kB 24.80%  bufio.NewReaderSize (inline)
  512.17kB 24.05%   100%   512.17kB 24.05%  google.golang.org/grpc/metadata.Join
         0     0%   100%   512.17kB 24.05%  cloud.google.com/go/secretmanager/apiv1.(*Client).AccessSecretVersion
         0     0%   100%   512.17kB 24.05%  cloud.google.com/go/secretmanager/apiv1.(*Client).AccessSecretVersion.func1
         0     0%   100%   512.17kB 24.05%  github.com/googleapis/gax-go/v2.Invoke
         0     0%   100%   512.17kB 24.05%  github.com/googleapis/gax-go/v2.invoke
         0     0%   100%   512.17kB 24.05%  google.golang.org/genproto/googleapis/cloud/secretmanager/v1.(*secretManagerServiceClient).AccessSecretVersion
         0     0%   100%   512.17kB 24.05%  google.golang.org/grpc.(*ClientConn).Invoke
         0     0%   100%  1617.50kB 75.95%  google.golang.org/grpc.(*addrConn).createTransport
```

And after many more requests:
```
$ go tool pprof heap.6.pprof
File: serverless-scheduler-proxy
Type: inuse_space
Time: May 4, 2021 at 9:50am (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 94.74MB, 94.49% of 100.26MB total
Dropped 26 nodes (cum <= 0.50MB)
Showing top 10 nodes out of 101
      flat  flat%   sum%        cum   cum%
   51.59MB 51.46% 51.46%    51.59MB 51.46%  google.golang.org/grpc/internal/transport.newBufWriter
   19.60MB 19.55% 71.01%    19.60MB 19.55%  bufio.NewReaderSize
    6.02MB  6.01% 77.02%     6.02MB  6.01%  bytes.makeSlice
    4.51MB  4.50% 81.52%    10.53MB 10.51%  crypto/tls.(*Conn).readHandshake
       4MB  3.99% 85.51%     4.50MB  4.49%  crypto/x509.parseCertificate
       3MB  2.99% 88.51%        3MB  2.99%  crypto/tls.Client
    2.50MB  2.49% 91.00%     2.50MB  2.49%  golang.org/x/net/http2/hpack.(*headerFieldTable).addEntry
    1.50MB  1.50% 92.50%     1.50MB  1.50%  google.golang.org/grpc/internal/grpcsync.NewEvent
       1MB     1% 93.50%        1MB     1%  runtime.malg
       1MB     1% 94.49%        1MB     1%  encoding/json.(*decodeState).literalStore
```

As we can see, `google.golang.org/grpc/internal/transport.newBufWriter` is taking up more and more memory. The only thing using gRPC in this app is `secretmanager`. From searching around, a common cause of this is not closing your gRPC connections.

I added a `Close` call after creating the client:
```go
	defer client.Close()
```

I restarted the server, sent another 500 requests, and `pprof` shows we found the culprit:
```
$ go tool pprof heap.8.with_close.pprof
File: serverless-scheduler-proxy
Type: inuse_space
Time: May 4, 2021 at 9:53am (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 2061.68kB, 100% of 2061.68kB total
Showing top 10 nodes out of 51
      flat  flat%   sum%        cum   cum%
  518.65kB 25.16% 25.16%   518.65kB 25.16%  google.golang.org/protobuf/internal/strs.(*Builder).AppendFullName
  516.64kB 25.06% 50.22%   516.64kB 25.06%  google.golang.org/protobuf/types/descriptorpb.init
  514.38kB 24.95% 75.17%   514.38kB 24.95%  google.golang.org/protobuf/internal/strs.(*Builder).MakeString (inline)
  512.01kB 24.83%   100%   512.01kB 24.83%  vendor/golang.org/x/net/http2/hpack.addDecoderNode
         0     0%   100%   514.38kB 24.95%  cloud.google.com/go/secretmanager/apiv1.(*Client).AccessSecretVersion.func1
         0     0%   100%  1033.03kB 50.11%  github.com/golang/protobuf/proto.Unmarshal
         0     0%   100%  1033.03kB 50.11%  github.com/golang/protobuf/proto.UnmarshalMerge
         0     0%   100%   514.38kB 24.95%  google.golang.org/genproto/googleapis/cloud/secretmanager/v1.(*secretManagerServiceClient).AccessSecretVersion
         0     0%   100%  1033.03kB 50.11%  google.golang.org/grpc.(*ClientConn).Invoke
         0     0%   100%  1033.03kB 50.11%  google.golang.org/grpc.(*clientStream).RecvMsg
```

**Closed** 2021-05-04 15:44 UTC
Labels: bot: owl-bot, priority: p1, type: bug
