### ISSUE TITLE
Merge on green not working

### ISSUE THREAD

**Issue by samtstern** [googleapis/repo-automation-bots#1369] opened 2021-02-05 11:50 UTC
See these two PRs:
- https://github.com/firebase/quickstart-testing/pull/95
- https://github.com/firebase/snippets-web/pull/102

In each case the `automerge` label was added pretty much immediately. The merge on green bot added the 👀 emoji to the PR so it seems to have noticed it but the required tests all passed hours ago and it hasn't been merged.

The only time I've gotten the bot to work is this PR, and that was after some label toggling:
https://github.com/firebase/snippets-web/pull/100

cc @sofisl

**Comment by sofisl** [comment] 2021-02-06 09:36
After speaking over email, this is an issue with the PRs not having reviewers. Duplicate of #1332, need to add instructions to the README.

**Closed by sofisl** 2021-02-06 09:36 UTC
Labels: triage me
